services:

  web:
    build: .
    container_name: web
    command: python3 manage.py runserver 0.0.0.0:8090
    volumes:
      - .:/code
    ports:
      - "8090:8090"
    depends_on:
      - db

  db:
    image: mdillon/postgis
    #command: -e POSTGRES_USER=johndoe -e POSTGRES_PASSWORD=myfakedata -e POSTGRES_DB=myfakedata library/postgres
    environment:
      - POSTGRES_USER=one
      - POSTGRES_PASSWORD="one"
      - POSTGRES_DB=one
    ports:
      - "5432:5432"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080